<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TdmsExtensionVersion>1.0.2</TdmsExtensionVersion>
	</PropertyGroup>

	<PropertyGroup>
		<TargetFramework>net6.0</TargetFramework>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
		<OutputPath>C:\Program Files (x86)\CSoft\TDMS Server 7.0\Extensions\ICommands</OutputPath>
	</PropertyGroup>

	<PropertyGroup>
		<Version>$(TdmsExtensionVersion)</Version>
		<AssemblyVersion>$(TdmsExtensionVersion)</AssemblyVersion>
		<FileVersion>$(TdmsExtensionVersion)</FileVersion>
	</PropertyGroup>

	<PropertyGroup>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
	</PropertyGroup>

	<PropertyGroup>
		<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
		<BaseOutputPath>C:\Program Files (x86)\CSoft\TDMS Server 7.0\Extensions\ICommands</BaseOutputPath>
		<Nullable>enable</Nullable>
	</PropertyGroup>
	
	<ItemGroup>
	  <Compile Remove="command2.cs" />
	</ItemGroup>

	<ItemGroup>
	  <Compile Remove="packages\**" />
	  <Compile Remove="TdmsExtension.iCommands.Tests\**" />
	  <EmbeddedResource Remove="packages\**" />
	  <EmbeddedResource Remove="TdmsExtension.iCommands.Tests\**" />
	  <None Remove="packages\**" />
	  <None Remove="TdmsExtension.iCommands.Tests\**" />
	</ItemGroup>

	<ItemGroup>
	  <None Remove="Config\appsettings.loc.json" />
	  <None Remove="Schema\OBJECT_DOCUMENT.vbs" />
	  <None Remove="Schema\OBJECT_DOCUMENT.xml" />
	</ItemGroup>

	<ItemGroup>
	  <EmbeddedResource Include="Config\appsettings.linux.json">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </EmbeddedResource>
	  <EmbeddedResource Include="Config\appsettings.production.json">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </EmbeddedResource>
	  <EmbeddedResource Include="Config\appsettings.loc.json">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </EmbeddedResource>
	  <EmbeddedResource Include="Schema\OBJECT_DOCUMENT.vbs">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </EmbeddedResource>
	  <EmbeddedResource Include="Schema\OBJECT_DOCUMENT.xml">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </EmbeddedResource>
	  <EmbeddedResource Include="TdmsExtension.iCommands.WebPart\content\assets\index-BS3Zmd53.js">
		  <Link>content\assets\index-BS3Zmd53.js</Link>
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </EmbeddedResource>
	  <EmbeddedResource Include="TdmsExtension.iCommands.WebPart\content\assets\index-B_SY1GJM.css">
		  <Link>content\assets\index-B_SY1GJM.css</Link>
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </EmbeddedResource>
	  <EmbeddedResource Include="TdmsExtension.iCommands.WebPart\content\index.html">
		  <Link>content\index.html</Link>
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </EmbeddedResource>
	  <EmbeddedResource Include="TdmsExtension.iCommands.WebPart\content\indexHello.html">
		  <Link>content\aindexHello.html</Link>
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </EmbeddedResource>
	  <EmbeddedResource Include="TdmsExtension.iCommands.WebPart\content\tdms.ico">
		  <Link>content\tdms.ico</Link>
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </EmbeddedResource>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Autofac" Version="6.3.0" />
		<PackageReference Include="Microsoft.AspNetCore.Cors" Version="2.3.0" />
		<PackageReference Include="Microsoft.AspNetCore.Mvc.Core" Version="2.2.5" />
		<PackageReference Include="Microsoft.Extensions.Configuration" Version="5.0.0" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="5.0.0" />
		<PackageReference Include="System.Drawing.Common" Version="9.0.8" />
		<PackageReference Include="Tdms.Web.Api" Version="7.0.162" />
	</ItemGroup>

</Project>
